### ISSUE TITLE
Có vẻ phương pháp này bị chiếm chuột và không thể chạy đa luồng

### ISSUE THREAD

**Issue by longnguyenQB** [tamnguyenvan/cloudflare-bypass#1]
Xin chào! Rất vui khi tìm được repo này của bạn! Bạn có cách nào có thể bypass cloudflare mà vẫn có thể chạy đa luồng (nhiều trình duyệt cùng lúc), nếu có thể thì không chiếm chuột càng tốt. Cảm ơn bạn rất nhiều!

**Comment by ChengHoward** [comment]
VM Deployment

**Comment by tamnguyenvan** [comment]
@longnguyenQB Đúng vậy. Phương pháp này không thể chạy đa luồng vì nó kiểm soát chuột. Bạn có thể dùng máy ảo như @ChengHoward gợi ý, hoặc sử dụng các giải pháp khác, như là proxy chẳng hạn.
