### ISSUE TITLE
Raspberry Pi & Chromium

### ISSUE THREAD

**Issue by creativepl-php** [tamnguyenvan/cloudflare-bypass#3]
Hi, I have script using Tampermonkey. Script runs for forms on website, but this website using turnstile. Your package will work with tampermonkey & chromium? I have no idea how this works technically, I understand that the code searches for an image on the screen, so it will find this image if it is in the Chromium window? If I understand correctly, the python script will run in the background and will always perform click actions if it finds a turnstile on the screen or I have to manually activate it somehow every time? Can you explain it to me?

**Comment by tamnguyenvan** [comment]
@creativepl-php , It automatically scans the screen for turnstile checkboxes and clicks them. Therefore, it functions only in GUI. Cheers
