### ISSUE TITLE
Does it work with chrome browser on macOS?

### ISSUE THREAD

**Issue by thedudster** [tamnguyenvan/cloudflare-bypass#4]
Hi, i'm looking for same bypass script but for my mac device running chrome browser. How do i make it work?

**Comment by tamnguyenvan** [comment]
I haven't tested it on macOS but in theory it should work. You need to install it using pip and use it in your Python code. How it works? It will take a screenshot of your screen and use template matching to detect Cloudfalre Turnsile. Then it will control your mouse to automatically click.
